-- Seed the full Signal Floor suggestion queue.
-- Run after supabase-schema.sql has created public.market_suggestions.

delete from public.market_suggestions;

insert into public.market_suggestions
  (id, suggestion_type, category, title, criteria, resolves_on, options, hr_approved)
values
  ('sdr_top_may', 'multiple', 'business', 'Who will be top SDR for May 2026?', 'Count #discos-booked posts where the SDR posts a new disco in May 2026. Tiebreaker: total GWh booked.', '2026-06-01', '["Moritz Hoffmann","Luis Feldhaeuser","Martin Ortiz Lopez","Chiara Lageveen","Field"]', false),
  ('hypothesis_tag_may', 'multiple', 'business', 'Most popular hypothesis tag in May 2026', 'Count H1 and H2 tags in #discos-booked during May 2026. Treat H1&H2 as 0.5 each.', '2026-06-01', '["H1","H2","Tie"]', false),
  ('may_gwh_bucket', 'multiple', 'business', 'Total GWh booked in May 2026', 'Sum all GWh figures posted in #discos-booked during May 2026.', '2026-06-01', '["Under 500 GWh","500-1000 GWh","1000-2000 GWh","Over 2000 GWh"]', false),
  ('arr_may_bucket', 'multiple', 'business', 'Total ARR of new closed-won deals in May 2026', 'Use official HubSpot or #full-team closed-won announcements for May 2026.', '2026-06-01', '["Under EUR 50k","EUR 50-100k","EUR 100-200k","Over EUR 200k"]', false),
  ('production_incidents_q2', 'multiple', 'business', 'Number of production incident announcements in Q2', 'Count production incident announcements in #product-important in Q2 2026.', '2026-07-01', '["0","1-2","3-5","6+"]', false),
  ('moss_receipts_may', 'multiple', 'fun', 'Total missing receipts on the last May Moss report', 'Use the final May Moss report and sum all missing receipts listed.', '2026-05-30', '["Under 80","80-120","120-180","Over 180"]', false),
  ('sdr_150', 'binary', 'business', 'Will the SDR team book at least 150 discos in May 2026?', 'YES if #discos-booked contains at least 150 valid new discovery-call posts between May 1 and May 31, 2026.', '2026-06-01', '[]', false),
  ('linked_in_shoutout', 'binary', 'business', 'Will any customer publicly post about ecoplanet on LinkedIn in May?', 'YES if a customer account or named customer employee posts a public ecoplanet-related LinkedIn shoutout in May 2026.', '2026-06-01', '[]', false),
  ('series_b', 'binary', 'rumor', 'Will ecoplanet announce a Series B by end of 2026?', 'YES if a Series B financing announcement is publicly made by December 31, 2026.', '2026-12-31', '[]', false),
  ('hundred_employees', 'binary', 'business', 'Will ecoplanet cross 100 employees by end of 2026?', 'YES if official headcount reaches at least 100 by December 31, 2026.', '2026-12-31', '[]', false),
  ('dance_floor_first', 'multiple', 'fun', 'Who will be first on the dance floor at the next company party?', 'Resolve by first clearly visible dancing moment at the next company party, using public photos, videos, or witness consensus.', '2026-07-01', '["Henry","Lukas","Erin","Basti","Field"]', false),
  ('negroni_count', 'multiple', 'fun', 'How many Negronis will be consumed by the core crew at the next party?', 'Resolve by honest post-party self-report or visible drink count from the group. Keep it playful and do not shame anyone.', '2026-07-01', '["0-3","4-7","8-12","13+"]', false),
  ('moss_top_may', 'multiple', 'fun', 'Who tops the May Moss wall of shame?', 'Use the final public May Moss report. If the named options do not win, Field wins.', '2026-05-30', '["Olivia","Basti","Max","Lukas","Field"]', false),
  ('kitchen_incident', 'multiple', 'fun', 'Most dramatic kitchen incident of Q2', 'Community vote at end of Q2 among incidents that were publicly visible in office channels.', '2026-07-01', '["Dishwasher drama","Frat-house rant","Oil bottle incident","New contender"]', false),
  ('doenerstag_count', 'multiple', 'fun', 'How many Doenerstag sightings happen in May?', 'Count public Slack mentions of Doener Tag, Doenerstag, or equivalent office lunch sightings in May.', '2026-06-01', '["0","1","2-3","4+"]', false),
  ('champagne_reactions', 'multiple', 'fun', 'Highest champagne reactions on one SDR post in May', 'Count champagne-style celebration reactions on the top single #discos-booked post in May.', '2026-06-01', '["0-3","4-5","6-8","9+"]', false),
  ('max_self_thanks', 'binary', 'fun', 'Will Max publicly thank himself in Q2?', 'YES if Max posts a clearly self-congratulatory or self-thanking message in a public company Slack channel during Q2.', '2026-07-01', '[]', false),
  ('bot_war', 'binary', 'fun', 'Will a Burkhard vs ecoplanet bot exchange happen in Q2?', 'YES if a public Slack thread contains a playful exchange between Burkhard and an ecoplanet AI/bot account before July 1.', '2026-07-01', '[]', false),
  ('schneckenrennen', 'binary', 'fun', 'Will Schneckenrennen be used to roast a slow project in Q2?', 'YES if someone uses snail race / Schneckenrennen language for a slow project in a public Slack channel during Q2.', '2026-07-01', '[]', false),
  ('almdudler', 'binary', 'fun', 'Will Almdudler keep going strong in Q2?', 'YES if Almdudler is referenced again in a public company channel before July 1.', '2026-07-01', '[]', false),
  ('dizzy_daisy', 'binary', 'fun', 'Will Dizzy Daisy be mentioned before the next party?', 'YES if Dizzy Daisy appears in a public party-planning or office-life Slack message before the next company party.', '2026-07-01', '[]', false),
  ('slot_jackpot', 'binary', 'fun', 'Will anyone hit the 250-credit Energy Slot jackpot this week?', 'YES if any user reports or the app records a 250-credit slot-machine payout within seven days of market launch.', '2026-05-05', '[]', false),
  ('clay_credit', 'binary', 'business', 'Will Max Jagi get public Clay-Leads credit at least once in May?', 'YES if Max Jagi is publicly credited or thanked for Clay-Leads work in #discos-booked or adjacent channels during May.', '2026-06-01', '[]', false),
  ('customer_praise', 'binary', 'business', 'Will any prospect say geile Software or equivalent praise in Q2?', 'YES if a prospect/customer quote with equivalent strong praise appears in a public Slack channel before July 1.', '2026-07-01', '[]', false),
  ('ronaldo_gif', 'binary', 'fun', 'Will the Ronaldo gif become the canonical #discos-booked celebration?', 'YES if the Ronaldo gif or a clearly equivalent reference appears at least three more times in #discos-booked during Q2.', '2026-07-01', '[]', false),
  ('q2_party_outcome', 'multiple', 'fun', 'What will be the most discussed next-party aftermath?', 'Resolve by Monday-after Slack consensus and visible public mentions.', '2026-07-01', '["Dance floor","Drinks","Lost item","Founder quote","Unexpected hero"]', false),
  ('office_treats', 'multiple', 'fun', 'How many cake or treat announcements happen in May?', 'Count public office messages offering cake, sweets, slices, snacks, or treats during May.', '2026-06-01', '["0-2","3-5","6-10","11+"]', false),
  ('first_big_arr', 'binary', 'business', 'Will any closed-won deal cross EUR 100k ARR in 2026?', 'YES if any official closed-won deal reaches at least EUR 100k ARR by December 31, 2026.', '2026-12-31', '[]', false),
  ('office_customer_spotting', 'binary', 'fun', 'Will someone spot a customer on the streets of Munich in May?', 'YES if a public #muc-office or equivalent message reports a real customer sighting in Munich during May.', '2026-06-01', '[]', false),
  ('burkhard_pun', 'binary', 'fun', 'Will Burkhard include a light-bulb or spark pun in May?', 'YES if Burkhard''s weekly recap includes a light, bulb, spark, energy, or similar pun during May.', '2026-06-01', '[]', false),
  ('public_departure_q2', 'spicy', 'people', 'Will any current employee publicly announce a departure in Q2?', 'YES if a current employee publicly announces their own departure in an official or broadly visible company channel during Q2. Already-announced exits do not count.', '2026-07-01', '[]', true),
  ('lilly_only_departure_q2', 'spicy', 'people', 'Will Lilly be the only publicly announced departure in Q2?', 'YES if Lilly remains the only pseudonymous/persona departure announced in broadly visible company channels during Q2. Already-announced Lilly exit counts as the baseline.', '2026-07-01', '[]', true),
  ('lilly_sendoff_speech', 'spicy', 'people', 'Will Lilly''s farewell speech become a top-3 Slack moment of the week?', 'YES if Lilly''s farewell speech or sendoff gets one of the three highest reaction counts in public company Slack during that week.', '2026-07-01', '[]', true),
  ('erin_wedding_next_event', 'spicy', 'people', 'Will Erin''s wedding be the next big company celebration topic?', 'YES if Erin''s wedding or wedding-adjacent celebration becomes the most discussed non-work celebration topic in public company channels before year-end.', '2026-12-31', '[]', true),
  ('next_wedding_character', 'spicy', 'people', 'Whose wedding becomes the next company lore moment?', 'Resolve by public company-channel mentions and reactions. Names are treated as anonymized in-game handles from the source file.', '2026-12-31', '["Erin","Henry","Lukas","Max","Field"]', true),
  ('customer_bankruptcy_public', 'spicy', 'business', 'Will any customer publicly file for insolvency before end of 2026?', 'YES only if insolvency is confirmed by a public legal filing or official public company statement. Rumors do not count.', '2026-12-31', '[]', true),
  ('customer_bankruptcy_trophy_bucket', 'spicy', 'business', 'Which customer bucket has the first public insolvency scare?', 'YES outcome is the bucket containing the first customer/prospect with public legal filing, official insolvency statement, or equivalent public distress confirmation before year-end. Rumors do not count.', '2026-12-31', '["Trophy accounts","Manufacturing","Healthcare","Logistics","No one"]', true),
  ('who_gets_roasted_next_allhands', 'spicy', 'people', 'Who gets playfully roasted at the next all-hands?', 'Resolve by public all-hands or Slack consensus. Only good-natured, work-context jokes count.', '2026-06-01', '["Sales","Product","Finance","Founders","No one dares"]', true),
  ('founder_quote_afterparty', 'spicy', 'people', 'Will a founder quote become the post-party meme?', 'YES if a founder quote from the next party is referenced at least three times in public Slack within one week after the event.', '2026-07-01', '[]', true),
  ('most_likely_to_vanish_after_party', 'spicy', 'people', 'Which team vanishes first after the next party?', 'Resolve by public party consensus. This is team-level only, no named individuals.', '2026-07-01', '["Sales","Product","Finance","People","Founders"]', true),
  ('flo_still_around', 'spicy', 'people', 'Will Flo''s farewell-but-still-around vibe persist in May?', 'YES if Flo posts in a public company Slack channel at least once in May after his farewell moment.', '2026-06-01', '[]', true),
  ('max_public_self_thanks', 'spicy', 'people', 'Will Max publicly thank himself again in Q2?', 'YES if Max posts a clearly self-thanking or self-crediting message in a public company channel during Q2.', '2026-07-01', '[]', true),
  ('lukas_finance_wrong', 'spicy', 'people', 'Will Lukas publicly admit a Finance forecast was wrong in Q2?', 'YES if Lukas publicly states or jokes that a Finance forecast, runway estimate, or planning number was wrong during Q2.', '2026-07-01', '[]', true);

